### ISSUE TITLE
Capturing formatting

### ISSUE THREAD

**Issue by Lyinggod** [D-first/quick-notes#1]
It is possible to capture the formatting from the chat. I have the following sample output
![image](https://user-images.githubusercontent.com/16379736/155889862-ab2de493-8453-42fe-a6f4-cc9e14d5ff17.png)

which results in the capture of 
![image](https://user-images.githubusercontent.com/16379736/155889896-0c300c3b-9e49-4ece-a5cf-7b17c3a60a80.png)

Can layout such as line breaks and text enhancements such as bold, italic, etc be retained?

**Comment by D-first** [comment]
Sorry for the delay.
Fixed.
